# Generated by Django 5.2 on 2025-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('hwid', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('activated_on', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(default=dict)),
            ],
        ),
    ]
