# Generated by Django 5.2 on 2025-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_license_email_license_last_hwid_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='hwid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
