# Generated by Django 5.2 on 2025-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_license_hwid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='last_hwid_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
